cooppizza/BI/BI/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'BI.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
)

cooppizza/cardapio/urls.py
from django.conf.urls import patterns, include, url
from cooppizza.cardapio import views

urlpatterns = patterns('',
	url(r'^$', views.indexCardapio, name='indexCardapio'),
	url(r'^pizza$', views.pizza, name='pizza'),
	url(r'^bebida$', views.bebida, name='bebida'),
	url(r'^ingrediente$', views.ingrediente, name='ingrediente'),
	url(r'^ingrediente/novo$', views.ingredienteNovo, name='ingredienteNovo'),
	url(r'^ingrediente/consulta/(?P<ingrediente_id>\d+)$', views.ingredienteConsulta, name='ingredienteConsulta'),
	url(r'^ingrediente/cadastrar$', views.ingredienteCadastrar, name='ingredienteCadastrar'),
	url(r'^ingrediente/(?P<ingrediente_id>\d+)/editar$', views.ingredienteEdita, name='ingredienteEdita'),
	url(r'^ingrediente/(?P<ingrediente_id>\d+)/alterar$', views.ingredienteAltera, name='ingredienteAltera'),
	url(r'^ingrediente/(?P<ingrediente_id>\d+)$', views.ingredienteDados, name='ingredienteDados'),
	url(r'^ingrediente/(?P<ingrediente_id>\d+)/deletar$', views.ingredienteDeletar, name='ingredienteDeletar'),
	url(r'^pizza/nova$', views.pizzaNova, name='pizzaNova'),
	url(r'^pizza/consulta/(?P<pizza_id>\d+)$', views.pizzaConsulta, name='pizzaConsulta'),
	url(r'^pizza/cadastrar$', views.pizzaCadastrar, name='pizzaCadastrar'),
	url(r'^pizza/(?P<pizza_id>\d+)$', views.pizzaDados, name='pizzaDados'),
	url(r'^pizza/(?P<pizza_id>\d+)/editar$', views.pizzaEdita, name='pizzaEdita'),
	url(r'^pizza/(?P<pizza_id>\d+)/alterar$', views.pizzaAltera, name='pizzaAltera'),
	url(r'^pizza/(?P<pizza_id>\d+)/ingredienteDaPizza$', views.pizzaIngrediente, name='pizzaIngrediente'),
	url(r'^pizza/(?P<pizza_id>\d+)/adicionar$', views.pizzaIngredienteAdiciona, name='pizzaIngredienteAdiciona'),
	url(r'^pizza/(?P<pizza_id>\d+)/deletar$', views.pizzaDeletar, name='pizzaDeletar'),
	url(r'^pizza/(?P<pizza_id>\d+)/(?P<pizzaingrediente_id>\d+)/deletarIngrediente$', views.pizzaDeletarIngrediente, name='pizzaDeletarIngrediente'),
	url(r'^bebida/nova$', views.bebidaNova, name='bebidaNova'),
	url(r'^bebida/consulta/(?P<bebida_id>\d+)$', views.bebidaConsulta, name='bebidaConsulta'),
	url(r'^bebida/cadastrar$', views.bebidaCadastrar, name='bebidaCadastrar'),
	url(r'^bebida/(?P<bebida_id>\d+)$', views.bebidaDados, name='bebidaDados'),
	url(r'^bebida/(?P<bebida_id>\d+)/editar$', views.bebidaEdita, name='bebidaEdita'),
	url(r'^bebida/(?P<bebida_id>\d+)/alterar$', views.bebidaAltera, name='bebidaAltera'),
	url(r'^bebida/(?P<bebida_id>\d+)/deletar$', views.bebidaDeletar, name='bebidaDeletar'),
	url(r'^lista$', views.listaProduto, name='lista'),
)

cooppizza/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
  url(r'^admin/', include(admin.site.urls)),
  url(r'^clientes/', include('cooppizza.clientes.urls')),
  url(r'^cardapio/', include('cooppizza.cardapio.urls')),
  url(r'^pedidos/', include('cooppizza.pedidos.urls')),
  url(r'^feedback/', include('cooppizza.formFeedback.urls')),
  url(r'^promocao/', include('cooppizza.promocao.urls')),
)

djangoTutorial/cardapio/polls/urls.py
from django.conf.urls import patterns, url

from polls import views

urlpatterns = patterns('',
    # ex: /polls/
    url(r'^$', views.IndexView.as_view(), name='index'),
    # ex: /polls/5/
    url(r'^specifics/(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
    # ex: /polls/5/results/
    url(r'^(?P<pk>\d+)/results/$', views.ResultsView.as_view(), name='results'),
    # ex: /polls/5/vote/
    url(r'^(?P<poll_id>\d+)/vote/$', views.vote, name='vote'),
)

cardapio/models.py
from django.db import models
import datetime
from django.utils import timezone

# Create your models here.

class Produto(models.Model):
    def __unicode__(self):
        return self.name
    name = models.CharField(max_length=200, unique=True)
    preco = models.DecimalField(max_digits=7, decimal_places=2)
    # promocao = models.BooleanField()
    # desconto = models.DecimalField(max_digits=7, decimal_places=2)

class Ingrediente(models.Model):
    def __unicode__(self):
        return self.name
    name = models.CharField(max_length=200, unique=True)
    quantidadeEstoque = models.DecimalField(max_digits=7, decimal_places=3)

class Pizza(models.Model):
    def __unicode__(self):
		return self.produto.name
    produto = models.ForeignKey(Produto)
    tipoDePizza = models.CharField(max_length=200)
    ingredientes = models.ManyToManyField(Ingrediente, through='PizzaIngrediente')

class Bebida(models.Model):
    def __unicode__(self):
		return self.produto.name
    produto = models.ForeignKey(Produto)

class PizzaIngrediente(models.Model):
	quantidadeDeUso = models.DecimalField(max_digits=7, decimal_places=3)
	pizza = models.ForeignKey(Pizza)
	ingrediente = models.ForeignKey(Ingrediente)

djangoTutorial/cardapio/polls/models.py
from django.db import models
import datetime
from django.utils import timezone

class Poll(models.Model):
    def __unicode__(self): 
	return self.question
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <  now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'
    question = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')


class Choice(models.Model):
    def __unicode__(self):
	return self.choice_text
    poll = models.ForeignKey(Poll)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

cooppizza/cardapio/views.py
from django.shortcuts import render, redirect
from django.template import RequestContext, loader
from django.core.urlresolvers import reverse
from django.http import HttpResponse, Http404
from django.core.exceptions import PermissionDenied

from cooppizza.cardapio.models import Produto, Pizza, Ingrediente, Bebida, PizzaIngrediente

# Create your views here.

def indexCardapio(request):
	template = loader.get_template('indexCardapio.html')
	return HttpResponse(template.render(RequestContext(request)))

def pizza(request):
	return render(request, 'pizza.html')

def bebida(request):
	return render(request, 'bebida.html')

def ingrediente(request):
	return render(request, 'ingrediente.html')

def ingredienteNovo(request):
	return render(request, 'ingredienteNovo.html')

def ingredienteCadastrar(request):
	if request.method == "POST":
		ingrediente = Ingrediente(nome=request.POST['nome'], marca=request.POST['marca'], descricao=request.POST['descricao'])
		ingrediente.save()
		return redirect(reverse('ingredienteDados', args=[ingrediente.id]))
	else:
		raise PermissionDenied

def ingredienteConsulta(request):
	if request.method == 'POST':
	    try:
	      ingrediente = Ingrediente.objects.get(nome=request.POST['nome'])
	    except (Ingrediente.DoesNotExist):
	      raise Http404
	    else:
	      return redirect(reverse('ingredienteDados', args=[ingrediente.id]))
	else:
  		raise PermissionDenied

def ingredienteAltera(request, ingrediente_id):
	try:
		ingrediente = Ingrediente.objects.get(pk=ingrediente_id)
	except (Ingrediente.DoesNotExist):
		raise Http404
	else: 
		return render(request, 'ingredienteAltera.html',
		 {'ingrediente':ingrediente})

def ingredienteEdita(request, ingrediente_id):
	if request.method == "POST":
		try:
			ingrediente = Ingrediente.objects.get(pk=ingrediente_id)
			ingrediente.quantidadeEstoque = request.POST['quantidadeEstoque']
			ingrediente.save()
		except (Ingrediente.DoesNotExist):
			raise Http404
		else: 
			return redirect(reverse('ingredienteDados', args=[ingrediente.id]))
	else:
  		raise PermissionDenied


def ingredienteDados(request, ingrediente_id):
	try:
		ingrediente = Ingrediente.objects.get(pk=ingrediente_id)
	except (Ingrediente.DoesNotExist):
		raise Http404
	else: 
		return render(request, 'ingredienteDados.html',
		 {'ingrediente':ingrediente})

def ingredienteDeletar(request, ingrediente_id):
  try:
    ingrediente = Ingrediente.objects.get(pk=ingrediente_id)
  except (Ingrediente.DoesNotExist):
    raise Http404
  else:
    ingrediente.delete()
    return redirect(reverse('ingrediente'))

def pizzaNova(request):
	return render(request, 'pizzaNova.html')

def pizzaCadastrar(request):
	if request.method == "POST":
		produto = Produto(nome=request.POST['nome'], preco=request.POST['preco'], isPizza=True)
		produto.save()
		pizza = Pizza(produto=produto, tipoDePizza = request.POST['tipoDePizza'], tamanho=request.POST['tamanho'])
		pizza.save()
		return redirect(reverse('pizzaDados', args=[pizza.id]))
	else:
		raise PermissionDenied

def pizzaConsulta(request):
	if request.method == 'POST':
	    try:
	      produto = Produto.objects.get(nome=request.POST['nome'])
	      pizza = Pizza.objects.get(produto=produto)
	    except (Pizza.DoesNotExist):
	      raise Http404
	    else:
	      return redirect(reverse('pizzaDados', args=[pizza.id]))
	else:
  		raise PermissionDenied

def pizzaAltera(request, pizza_id):
	try:
		pizza = Pizza.objects.get(pk=pizza_id)
	except (Pizza.DoesNotExist):
		raise Http404
	else: 
		return render(request, 'pizzaAltera.html',
		 {'pizza':pizza})

def pizzaEdita(request, pizza_id):
	if request.method == "POST":
		try:
			pizza = Pizza.objects.get(pk=pizza_id)
			produto = pizza.produto
			produto.preco = request.POST['preco']
			produto.save()
		except (Pizza.DoesNotExist):
			raise Http404
		else: 
			return redirect(reverse('pizzaDados', args=[pizza.id]))
	else:
  		raise PermissionDenied

def pizzaDados(request, pizza_id):
	try:
		pizza = Pizza.objects.get(pk=pizza_id)
	except (Pizza.DoesNotExist):
		raise Http404
	else: 
		return render(request, 'pizzaDados.html',
		 {'pizza':pizza})

def pizzaDeletar(request, pizza_id):
  try:
    pizza = Pizza.objects.get(pk=pizza_id)
    produto = pizza.produto
  except (Pizza.DoesNotExist):
    raise Http404
  else:
    pizza.delete()
    produto.delete()
    return redirect(reverse('pizza'))

def pizzaDeletarIngrediente(request, pizza_id, pizzaingrediente_id):
  try:
    pizza = Pizza.objects.get(pk=pizza_id)
    pizzaIngrediente = PizzaIngrediente.objects.get(pk=pizzaingrediente_id)
  except (Pizza.DoesNotExist):
    raise Http404
  else:
    pizzaIngrediente.delete()
    return redirect(reverse('pizzaDados', args=[pizza.id]))

def pizzaIngrediente(request, pizza_id):
	try:
		pizza = Pizza.objects.get(pk=pizza_id)
		ingredientes = Ingrediente.objects.all().order_by('nome')
	except (Pizza.DoesNotExist):
		raise Http404
	else: 
		return render(request, 'pizzaIngrediente.html',
		 {'pizza':pizza, 'ingredientes':ingredientes})

def pizzaIngredienteAdiciona(request, pizza_id):
	if request.method == "POST":
		try:
			ingrediente = Ingrediente.objects.get(nome=request.POST['nome'])
			pizza = Pizza.objects.get(pk=pizza_id)
			if request.POST.__contains__('isRecheio'):
				pizzaIngrediente = PizzaIngrediente(quantidadeDeUso=request.POST['quantidadeDeUso'], pizza=pizza, ingrediente=ingrediente, medida=request.POST['medida'], isRecheio=True) 
			else:
				pizzaIngrediente = PizzaIngrediente(quantidadeDeUso=request.POST['quantidadeDeUso'], pizza=pizza, ingrediente=ingrediente, medida=request.POST['medida'], isRecheio=False) 
			pizzaIngrediente.save()
		except (Ingrediente.DoesNotExist):
			raise Http404
		else: 
			return redirect(reverse('pizzaDados', args=[pizza.id]))
	else:
  		raise PermissionDenied

def bebidaNova(request):
	return render(request, 'bebidaNova.html')

def bebidaCadastrar(request):
	if request.method == "POST":
		produto = Produto(nome=request.POST['nome'], preco=request.POST['preco'], isPizza=False)
		produto.save()
		bebida = Bebida(produto=produto)
		bebida.save()
		return redirect(reverse('bebidaDados', args=[bebida.id]))
	else:
		raise PermissionDenied

def bebidaConsulta(request):
	if request.method == 'POST':
	    try:
	      produto = Produto.objects.get(nome=request.POST['nome'])
	      bebida = Bebida.objects.get(produto=produto)
	    except (Bebida.DoesNotExist):
	      raise Http404
	    else:
	      return redirect(reverse('bebidaDados', args=[bebida.id]))
	else:
  		raise PermissionDenied

def bebidaAltera(request, bebida_id):
	try:
		bebida = Bebida.objects.get(pk=bebida_id)
	except (Bebida.DoesNotExist):
		raise Http404
	else: 
		return render(request, 'bebidaAltera.html',
		 {'bebida':bebida})

def bebidaEdita(request, bebida_id):
	if request.method == "POST":
		try:
			bebida = Bebida.objects.get(pk=bebida_id)
			produto = bebida.produto
			produto.preco = request.POST['preco']
			produto.save()
		except (Bebida.DoesNotExist):
			raise Http404
		else: 
			return redirect(reverse('bebidaDados', args=[bebida.id]))
	else:
  		raise PermissionDenied

def bebidaDados(request, bebida_id):
	try:
		bebida = Bebida.objects.get(pk=bebida_id)
	except (Bebida.DoesNotExist):
		raise Http404
	else: 
		return render(request, 'bebidaDados.html',
		 {'bebida':bebida})

def bebidaDeletar(request, bebida_id):
  try:
    bebida = Bebida.objects.get(pk=bebida_id)
    produto = bebida.produto
  except (Bebida.DoesNotExist):
    raise Http404
  else:
    bebida.delete()
    produto.delete()
    return redirect(reverse('bebida'))

def listaProduto(request):
	produtos = Produto.objects.all().order_by('-preco')
	return render(request, 'listaProduto.html', {'produtos':produtos})

djangoTutorial/cardapio/polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic
from django.utils import timezone

from polls.models import Choice, Poll

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_poll_list'

    def get_queryset(self):
        """Return the last five published polls."""
        return Poll.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Poll
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Poll
    template_name = 'polls/results.html'

def vote(request, poll_id):
    p = get_object_or_404(Poll, pk=poll_id)
    try:
        selected_choice = p.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the poll voting form.
        return render(request, 'polls/detail.html', {
            'poll': p,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(p.id,)))

cooppizza/cardapio/templates/bebida.html
{% extends "indexCardapio.html" %}

		{% load staticfiles %}

		{% block stylesheets %}
			{{ block.super }}

			<link href="{% static "css/rh/rh_list.css" %}" rel="stylesheet">

		{% endblock %}

		{% block title %}
				CooPizza - Bebida
		{% endblock %}

		{% block content %}

		<h1>Cadastrar Bebida</h1>
		  <div class="element">
		    <!-- add -->
		    <a type="button" href="{% url 'bebidaNova' %}" class="btn btn-lg btn-success btn-add">
		    	<span class="glyphicon glyphicon-plus"></span>
		    </a>
		  </div>

    			<table class ="table table-striped table-hover">
				<tr>

				<th style="text-align: center;">Nome</th>
				<th style="text-align: center;">Preço</th>
				<th style="text-align: center;">Modificar</th>
			
				</tr>

				<h1> Bebidas </h1>

				{% for bebida in bebidas %}
				      	<tr>
				        	<td style="text-align: center;" >{{ bebida.produto.nome }}</td>
			            	<td style="text-align: center;">R$ {{ bebida.produto.preco }}</td>
				        	<td style="text-align: center;">
				          	<div class="element">
				                <a type="button" class="btn btn-small btn-primary" href="{% url 'bebidaConsulta' bebida.id %}">
				                      <span class="glyphicon glyphicon-pencil"></span>
				                </a>
			            	</div>
				        	</td>
				        </tr>
			    {% endfor %}
			    </table>
		{% endblock %}

cooppizza/cardapio/templates/bebidaAltera.html
{% extends "indexCardapio.html" %}

    {% load staticfiles %}

    {% block stylesheets %}
      {{ block.super }}

      <link href="{% static "css/rh/rh_list.css" %}" rel="stylesheet">

    {% endblock %}

    {% block title %}
        CooPizza - Altera Bebida
    {% endblock %}

    {% block content %}
<h1>{{ bebida.produto.nome }}
    <a type="button" class="btn btn-small btn-danger" href="{% url 'bebidaDeletar' bebida.id %}">
                    <span class="glyphicon glyphicon-remove"></span>
                </a></h1> 
    <h4>Preço:</h4> 
    <div class="form">
      <form method="post" action="{% url 'bebidaEdita' bebida.id %}">
        {% csrf_token%}
        <ul>
          <li>
            <input type="number" name="preco" step="0.01" min ="0"/>
            <input type="submit" value="Alterar"/>
          </li>
        </ul>
    </div> 
    {% endblock %}

cooppizza/cardapio/templates/bebidaDados.html
{% extends "indexCardapio.html" %}

    {% load staticfiles %}

    {% block stylesheets %}
      {{ block.super }}

      <link href="{% static "css/rh/rh_list.css" %}" rel="stylesheet">

    {% endblock %}

    {% block title %}
        CooPizza - Bebida {{bebida.produto.nome}}
    {% endblock %}

    {% block content %}
<h1>{{ bebida.produto.nome }}
    <a type="button" class="btn btn-small btn-danger" href="{% url 'bebidaDeletar' bebida.id %}">
                    <span class="glyphicon glyphicon-remove"></span>
                </a></h1>
    <h4>Preço:</h4> R$ {{bebida.produto.preco}} 
        <a type="button" class="btn btn-small btn-primary" href="{% url 'bebidaAltera' bebida.id %}">
            <span class="glyphicon glyphicon-pencil"></span>
        </a>
    {% endblock %}

cooppizza/cardapio/templates/bebidaNova.html
{% extends "indexCardapio.html" %}

		{% load staticfiles %}

		{% block stylesheets %}
			{{ block.super }}

			<link href="{% static "css/rh/rh_list.css" %}" rel="stylesheet">

		{% endblock %}

		{% block title %}
				CooPizza - Nova Bebida
		{% endblock %}

		{% block content %}

		<h1>Bebida</h1>
		<br>
		<div class="form">
			<form method="post" action="{% url 'bebidaCadastrar' %}">
				{% csrf_token%}
				<ul>
					<li>
						<label>Nome:</label>
						<input type="text" name="nome" value="" /> 
					</li>
					<li>
						<label>Preço:</label>
						<input type="number" name="preco" step="0.01" min ="0" value="" /> 
					</li>
					<br>
						<input type="submit" value="Cadastrar"/>
				</ul>
		</div>
		{% endblock %}

cooppizza/cardapio/templates/indexCardapio.html
{% extends "index.html" %}
{% load staticfiles %}


{% block navbar_links %}
<li class="active"><a href="#">Principal</a></li>
<li><a href="#">Pedido</a></li>
<li><a href="#">BI</a></li>
<li><a href="#">Marketing/Feedback</a></li>
{% endblock %}

{% block sidebar %}
    <div class="col-sm-3 col-md-2 sidebar">
      <ul class="nav nav-sidebar">
      	{% block sidebar_links %}
	        <li><a href="pizza">Pizza</a></li>
	        <li><a href="bebida">Bebida</a></li>
	        <li><a href="ingrediente">Ingrediente</a></li>
        {% endblock %}
      </ul>
    </div>
{% endblock %}

{% block content %}
{% comment %}<h1 class="page-header">Bem Vindo</h1>{% endcomment %}
<div class="jumbotron">
	<h1 class="text-center">CooPizza</h1>
	<p class="lead text-justify"> Melhor ERP para pizzarias.</p>
</div>
{% endblock %}

cooppizza/cardapio/templates/ingredienteAltera.html
{% extends "indexCardapio.html" %}

    {% load staticfiles %}

    {% block stylesheets %}
      {{ block.super }}

      <link href="{% static "css/rh/rh_list.css" %}" rel="stylesheet">

    {% endblock %}

    {% block title %}
        CooPizza - Ingrediente {{pizza.nome}}
    {% endblock %}

    {% block content %}
<h1>Ingrediente {{ ingrediente.nome }}
    <a type="button" class="btn btn-small btn-danger" href="{% url 'ingredienteDeletar' ingrediente.id %}">
                    <span class="glyphicon glyphicon-remove"></span>
                </a></h1>
    <h4>Marca: {{ingrediente.marca}} </h4> 
    <h4>Descrição:</h4> {{ingrediente.descricao}} 
    {% endblock %}

cooppizza/cardapio/templates/pizzaAltera.html
    {% extends "indexCardapio.html" %}

    {% load staticfiles %}

    {% block stylesheets %}
      {{ block.super }}

      <link href="{% static "css/rh/rh_list.css" %}" rel="stylesheet">

    {% endblock %}

    {% block title %}
        CooPizza - Altera Pizza
    {% endblock %}

    {% block content %}
<h1>Pizza {{ pizza.produto.nome }}
    <a type="button" class="btn btn-small btn-danger" href="{% url 'pizzaDeletar' pizza.id %}">
                    <span class="glyphicon glyphicon-remove"></span>
                </a></h1>
    <h4>Tamanho {{pizza.tamanho}} </h4> 
    <h4>Preço:</h4> 
    <div class="form">
      <form method="post" action="{% url 'pizzaEdita' pizza.id %}">
        {% csrf_token%}
        <ul>
          <li>
            <input type="number" name="preco" step="0.01" min ="0"/>
            <input type="submit" value="Alterar"/>
          </li>
        </ul>
    </div> 
    <h1> Composição da Pizza - Recheios </h1>
    <ul>
{% for pizzaingrediente in pizza.pizzaingrediente_set.all %}
            <li> {{ pizzaingrediente.ingrediente }} - {{ pizzaingrediente.quantidadeDeUso }} -
        {% if pizzaingrediente.medida == 'KG'%}
        kilograma{{ pizzaingrediente.quantidadeDeUso|pluralize }}
        {% endif %}
        {% if pizzaingrediente.medida == 'PT'%}
        Pitada{{ pizzaingrediente.quantidadeDeUso|pluralize }}
        {% endif %}
        {% if pizzaingrediente.medida == 'XC'%}
        Xícaras{{ pizzaingrediente.quantidadeDeUso|pluralize }}
        {% endif %}
        {% if pizzaingrediente.medida == 'CL'%}
        Colher{{ pizzaingrediente.quantidadeDeUso|pluralize }}
        {% endif %}
        <a type="button" class="btn btn-small btn-danger" href="{% url 'pizzaDeletarIngrediente' pizza.id pizzaingrediente.id %}">
                    <span class="glyphicon glyphicon-remove"></span>
                </a>
{% endfor %}
    </ul>
    <a type="button" href="{% url 'pizzaIngrediente' pizza.id %}" class="btn btn-small btn-success btn-add">
                Adicionar ingrediente à pizza
            </a>
    <br>
    <br>
    <a type="button" href="http://gnt.globo.com/receitas/Conversor-de-medidas-para-receitas.shtml" class="btn btn-small btn-success btn-add" target="_blank">
                Auxílio para conversão de medidas
            </a>
    {% endblock %}

cooppizza/cardapio/templates/pizzaDados.html
{% extends "indexCardapio.html" %}

    {% load staticfiles %}

    {% block stylesheets %}
      {{ block.super }}

      <link href="{% static "css/rh/rh_list.css" %}" rel="stylesheet">

    {% endblock %}

    {% block title %}
        CooPizza - Pizza {{pizza.produto.nome}}
    {% endblock %}

    {% block content %}
<h1>Pizza {{ pizza.produto.nome }}
    <a type="button" class="btn btn-small btn-danger" href="{% url 'pizzaDeletar' pizza.id %}">
                    <span class="glyphicon glyphicon-remove"></span>
                </a></h1>
    <h4>Tamanho {{pizza.tamanho}} </h4> 
    <h4>Preço:</h4> R$ {{pizza.produto.preco}} 
        <a type="button" class="btn btn-small btn-primary" href="{% url 'pizzaAltera' pizza.id %}">
            <span class="glyphicon glyphicon-pencil"></span>
        </a>
    <h1> Composição da Pizza - Recheios </h1>
    <ul>
{% for pizzaingrediente in pizza.pizzaingrediente_set.all %}
      <li> {{ pizzaingrediente.ingrediente }} - {{ pizzaingrediente.quantidadeDeUso }} -
        {% if pizzaingrediente.medida == 'KG'%}
        kilograma{{ pizzaingrediente.quantidadeDeUso|pluralize }}
        {% endif %}
        {% if pizzaingrediente.medida == 'PT'%}
        Pitada{{ pizzaingrediente.quantidadeDeUso|pluralize }}
        {% endif %}
        {% if pizzaingrediente.medida == 'XC'%}
        Xícaras{{ pizzaingrediente.quantidadeDeUso|pluralize }}
        {% endif %}
        {% if pizzaingrediente.medida == 'CL'%}
        Colher{{ pizzaingrediente.quantidadeDeUso|pluralize }}
        {% endif %}
        <a type="button" class="btn btn-small btn-danger" href="{% url 'pizzaDeletarIngrediente' pizza.id pizzaingrediente.id %}">
                    <span class="glyphicon glyphicon-remove"></span>
                </a>
{% endfor %}
    </ul>
    <a type="button" href="{% url 'pizzaIngrediente' pizza.id %}" class="btn btn-small btn-success btn-add">
                Adicionar ingrediente à pizza
            </a>
    <br>
    <br>
    <a type="button" href="http://gnt.globo.com/receitas/Conversor-de-medidas-para-receitas.shtml" class="btn btn-small btn-success btn-add" target="_blank">
                Auxílio para conversão de medidas
            </a>
    {% endblock %}